; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.30"

; Modules
projects[admin_menu][version] = "3.0-rc4"

projects[ctools][version] = "1.4"

projects[entity][version] = "1.5"

projects[features][version] = "2.0"

projects[jquery_update][version] = "2.4"

projects[libraries][version] = "2.2"

projects[module_filter][version] = "1.8"

projects[services][version] = "3.7"

projects[services_entity][version] = "2.0-alpha7"

projects[uuid][version] = "1.0-alpha5"

projects[views][version] = "3.8"
